export const songs = [
  {
    id: 1,
    name: "Skyfall",
    artist: "Adel",
    album: "Skyfall",
    time: "4:47",
  },
  {
    id: 2,
    name: "Train",
    artist: "Brick+Mortar",
    album: "Dropped",
    time: "3:05",
  },
  {
    id: 3,
    name: "Houdini",
    artist: "Foster the People",
    album: "Torches",
    time: "3:24",
  },
  {
    id: 4,
    name: "The Scientist",
    artist: "Coldplay",
    album: "X&Y",
    time: "4:18",
  },
  {
    id: 5,
    name: "Black Betty",
    artist: "Caravan Palace",
    album: "Black Betty-Single",
    time: "3:10",
  },
  {
    id: 6,
    name: "Backing Off",
    artist: "Champion",
    album: "Champion",
    time: "2:53",
  },
  {
    id: 7,
    name: "Imagination",
    artist: "Foster the People",
    album: "Imagination-Single",
    time: "4:16",
  },
  {
    id: 8,
    name: "On Melancholy Hill",
    artist: "Gorillaz",
    album: "Plastic Beach",
    time: "3:54",
  },
  {
    id: 9,
    name: "Closer",
    artist: "Lemaitre",
    album: "Closer",
    time: "4:32",
  },
  {
    id: 10,
    name: "Ghenghis Khan",
    artist: "Miike Snow",
    album: "iii",
    time: "3:32",
  },
];
